#pragma once
#define MAX_FORREST_SIZE 1024
#define MAX_STRING_LENGTH MAX_FORREST_SIZE*MAX_FORREST_SIZE
#define MAX_INPUT_STRING_LENGTH MAX_FORREST_SIZE*4
#define TIMEOUT_IN_MILLISECONDS 5000
#define BRUTAL_TERMINATION_CODE 0x55
#define BUFFER_SIZE MAX_STRING_LENGTH
